project:
  type: book
  output-dir: docs

book:
  title: "Stat112 Notebook"
  author: "Tanisha Dodla"
  date: "2024 Fall"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/data_viz.qmd
      - activities/bivariate_viz.qmd
      - activities/multivariate_viz.qmd
    
    - part: notes/README.qmd
      chapters: 
      - notes/Chapter-2.qmd
      - notes/Chapter-3.qmd
      - notes/Chapter-4.qmd
      - notes/Chapter-5.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
