project:
  type: book
  output-dir: docs

book:
  title: "Stat112 Notebook"
  author: "Tanisha Dodla"
  date: "2024 Fall"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/data_viz.qmd
      - activities/bivariate_viz.qmd
      - activities/multivariate_viz.qmd
      - activities/spatial_viz.qmd
      - activities/effective_viz.qmd
      - activities/wrangling_functions.qmd
      - activities/Wrangling_practice.qmd
      - activities/Reshaping_data.qmd
      - activities/Joining_data.qmd
      - activities/factors.qmd
      - activities/Strings.qmd
      - activities/Data_import.qmd
    
    - part: notes/README.qmd
      chapters: 
      - notes/Chapter-2.qmd
      - notes/Chapter-3.qmd
      - notes/Chapter-4.qmd
      - notes/Chapter-5.qmd
      - notes/Chapter-6.qmd
      - notes/Chapter-7.qmd
      - notes/Review.qmd 
      - notes/Chapter-8.qmd
      - notes/Chapter-9.qmd
      - notes/Chapter-10.qmd
      - notes/Chapter-11.qmd
      - notes/Chapter-12.qmd
      - notes/Chapter-13.qmd
      - notes/Chapter-15.qmd
      - notes/Chapter-16.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
